apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:8599786fcb8414a220939c62e464d4e269cf630e83510211e4ff69f468a00965
  name: quay.io/balki404/py-app-gha
  newName: quay.io/balki404/py-app-gha
