apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:3e834f7f34101baaf468ed8cf104d2d199cf89251fe234f85c7afe1cf264e5f3
  name: dotnet-7.0
  newName: quay.io/balki404/dotnet-7.0
