apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:fd51419b5d61d153c6b1204e4c1718a9d9fe623d7bf7d505f0c33b2c5cda6ecf
  name: quay.io/balki404/py-app-gha
  newName: quay.io/balki404/py-app-gha
