apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:373772203857f2784174d99b90d5d4df7e81f3a6dc8ebf5048d752125104c4e5
  name: quay.io/balki404/py-app-gha
  newName: quay.io/balki404/py-app-gha
