apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:d7b41964cb55fad09093bd96c67fd77c08391d54f43f26a4150b838be5c29895
  name: dotnet-7.0
  newName: quay.io/balki404/dotnet-7.0
