apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py-app-staging
  namespace: openshift-gitops
spec:
  destination:
    namespace: py-app-staging
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: environment/staging
    repoURL: https://github.com/bbalakriz/sample-python-basic-gitops
    targetRevision: master
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
