apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-python-basic
  name: sample-python-basic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample-python-basic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-python-basic
        deployment: sample-python-basic
    spec:
      containers:
      - image: quay.io/balki404/py-app-gha:latest
        imagePullPolicy: Always
        name: sample-python-basic
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: quay
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
