apiVersion: v1
kind: Service
metadata:
  labels:
    app: dnapp
  name: dnapp
  namespace: balki404-dev
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
  selector:
    app: dnapp
    deployment: dnapp
